name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - run: chmod +x ./gradlew
      - run: ./gradlew build
      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.QBOX_HOST }}
          username: ${{ secrets.QBOX_USER }}
          key: ${{ secrets.QBOX_SERVER_KEY }}
          source: "build/libs/qbox-server-0.0.1-SNAPSHOT.jar"
          target: "server/"
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QBOX_HOST }}
          username: ${{ secrets.QBOX_USER }}
          key: ${{ secrets.QBOX_SERVER_KEY }}
          script: |
            cd server/build/libs
            sudo kill $(sudo lsof -t -i:8080)
            nohup java -jar qbox-server-0.0.1-SNAPSHOT.jar 1>nohup/stdout.txt 2>nohup/stderr.txt &
            
            sudo service nginx restart


